Repository kemboijs/nodejs-api-cli, pull requests merged in 2020-02, with the labels that each got.

#46 #45 setup Postgres database without using ORM
  bin/createapp.js
  bin/createmaindir.js
  bin/createsrcdirandfiles.js
  bin/installingdependancies.js
  tasks/data.js
Labels: needs update

#52 rename from kemboijs-cli to nodejs-api-cli
  README.md
  package-lock.json
  package.json
Labels: ready for review

#49 folder restructuring
  bin/createapp.js
  bin/createroutedirfile.js
  bin/createsrcdirandfiles.js
  package.json
  tasks/app.js
  tasks/config/babel.js
  tasks/config/envexample.js
  tasks/config/gitignore.js
  tasks/config/packagejson.js
  tasks/config/readme.js
  tasks/controllers/index.js
  tasks/controllers/noormuser.js
  tasks/controllers/user.js
  tasks/data.js
  tasks/database/createdb.js
  tasks/database/dropdb.js
  tasks/database/noormcreatedb.js
  tasks/database/noormdropdb.js
  tasks/database/nosequelizesetup.js
  tasks/database/userqueries.js
  tasks/index.js
  tasks/middlewares/index.js
  tasks/middlewares/user.js
  tasks/models/nosequelizeusermodel.js
  tasks/models/sequelizeusermodel.js
  tasks/routes/index.js
  tasks/routes/user.js
  tasks/tests/index.js
Labels: unfinished-pr

#63 Create FUNDING.yml
  .github/FUNDING.yml
Labels: ready to land

#61 fix console issues and update readme
  README.md
  bin/installingdependancies.js
  tasks/config/packagejson.js
Labels: ready for review

#65 Improve folder structure for tests
  README.md
  bin/createsrcdirandfiles.js
  bin/openandappendfile.js
  package-lock.json
  package.json
  tasks/config/packagejson.js
  tasks/index.js
  tasks/tests/middleware.js
  tasks/tests/routes.js
  tasks/tests/userController.js
Labels: ready for review

#64 add support for mongodb and mongoose
  bin/createapp.js
  bin/createsrcdirandfiles.js
  tasks/controllers/mongodbcontroller.js
  tasks/database/mongodbsetup.js
  tasks/helpers/servererrorhandler.js
  tasks/index.js
  tasks/models/mongodbusermodel.js
  tasks/routes/user.js
Labels: ready for review

#69 Update issue templates -> feature request & bug report
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ready to land

#67 add helper function for handling response in the generated app
  bin/createsrcdirandfiles.js
  tasks/controllers/mongodbcontroller.js
  tasks/controllers/noormuser.js
  tasks/controllers/user.js
  tasks/helpers/responsehelper.js
  tasks/index.js
Labels: ready to land
